### PR TITLE
Update to use Ghost {{content}}

### LINKED ISSUE #4: Page content should be user-updatable
The content for the pages at the moment is all embedded within the theme, which makes it inaccessible for other people to update. While some pages might need special treatment in the theme, using [`{{content}}`](https://github.com/TryGhost/Casper/blob/master/page.hbs#L46) would let users still be able to edit most things.

### PR DESCRIPTION
**Pull request by farfamahar**
Content handle bars added to donate page and home page

### CODE REVIEW

**Comment by farfamahar** [comment]
I had to update the routes file to get it to work. This is what I have https://pastebin.com/tPgheqiD

Taken from this guide https://ghost.org/tutorials/custom-home-page/ (Section 2)

**Review by backspace — CHANGES_REQUESTED** [review]
Hey, thanks for working on this! I made a suggestion in a separate PR: #16 

My instinct is to have as few custom templates as possible to maximise the content that’s user-editable. That PR deletes `page-donate.hbs` entirely and adds `page.hbs` as the base template for any page, in case anyone needs to add one. You can see it in action at the [preview deployment donation page](https://ghostprev-content-without-dona.herokuapp.com/donate/), whose content is entirely editable in the admin UI. I also added an [other page](https://ghostprev-content-without-dona.herokuapp.com/other/) to demonstrate that base template capability.

This has the added benefit of not needing any changes to `routes.yaml`.

What do you think?? 😯

**Comment by backspace** [comment]
Incidentally, I’m sorry for [this spurious failing test](https://github.com/winnipegpolicecauseharm/wpch-ghost-theme/pull/12/checks?check_run_id=1069644149); I naïvely copied the Casper test workflow without actually having the correct scripts and dependency! It’s fixed as of ec989bf.

**Comment by farfamahar** [comment]
Oooh yeah. Base page template definitely seems like the best way to go about this.

**Comment by backspace** [comment]
thanks for looking, I meant to make that merge into this one, not `main`, so now this one is outdated, sorry!!!

**Pull request closed without merging**
